# Generated by Django 4.2.3 on 2023-09-16 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contdb',
            name='mail',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='contdb',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
